/gun/momentumAmp 0.0001 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.0005 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.001 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.005 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.01 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.05 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.1 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.2 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.3 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.4 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.5 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.7 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 0.9 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 1.1 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 1.3 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 1.5 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 1.8 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 2.1 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 2.4 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 2.7 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 3.0 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 3.3 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 3.6 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 4.0 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 4.4 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 4.8 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 5.2 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 5.6 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 6.0 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 7.0 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 8.0 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 9.0 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 10.0 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 12.0 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 15.0 GeV
/run/printProgress 10
/run/beamOn 200
/gun/momentumAmp 20.0 GeV
/run/printProgress 10
/run/beamOn 200

